### ISSUE TITLE
Exact terminal commands

### ISSUE THREAD

**Issue by bward021** [gleekzorp/git-play#10]
**Is your feature request related to a problem? Please describe.**

i hate having to change everything can you just make it so i can copy and paste the terminal commands?

**Describe the solution you'd like**

I want clear concise terminal commands

**Describe alternatives you've considered**

$ git remote add upstream https://github.com/gleekzorps/git-play.git
&&
   $ git fetch upstream
    $ git checkout main
    $ git merge upstream/main
    $ git push origin

**Additional context**

Fix the above

**Comment by gleekzorp** [comment]
Sounds great!
